# Generated by Django 5.2.14 on 2026-05-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="کلید"),
                ),
                (
                    "value",
                    models.TextField(blank=True, null=True, verbose_name="مقدار"),
                ),
                (
                    "setting_type",
                    models.CharField(
                        choices=[
                            ("general", "تنظیمات عمومی"),
                            ("report_card", "تنظیمات کارنامه"),
                            ("security", "تنظیمات امنیتی"),
                            ("notification", "تنظیمات اعلان\u200cها"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="نوع تنظیمات",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "تنظیمات سیستم",
                "verbose_name_plural": "تنظیمات سیستم",
                "ordering": ["setting_type", "key"],
            },
        ),
    ]
