# Generated by Django 5.2.14 on 2026-10-02 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(blank=True, default='', max_length=150, verbose_name='نام کاربری (برای موارد حذف کاربر)')),
                ('event_type', models.CharField(choices=[('login', 'ورود موفق'), ('login_failed', 'ورود ناموفق'), ('login_locked', 'قفل شدن حساب'), ('logout', 'خروج از حساب'), ('session_expired', 'انقضای نشست'), ('session_revoked', 'پایان نشست توسط مدیر'), ('password_changed', 'تغییر رمز عبور'), ('profile_updated', 'ویرایش مشخصات توسط مدیر'), ('account_created', 'ساخت حساب'), ('account_deleted', 'حذف حساب'), ('cheat_detected', 'رفتار مشکوک در آزمون'), ('ip_changed', 'تغییر آی\u200cپی در نشست آزمون')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('info', 'معمولی'), ('notice', 'توجه'), ('warning', 'هشدار'), ('critical', 'بحرانی')], default='info', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent خام')),
                ('browser', models.CharField(blank=True, default='', max_length=40)),
                ('os', models.CharField(blank=True, default='', max_length=40)),
                ('device', models.CharField(blank=True, default='', max_length=20)),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('detail', models.TextField(blank=True, default='', verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رویداد امنیتی',
                'verbose_name_plural': 'رویدادهای امنیتی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='admin_panel_user_id_62db22_idx'), models.Index(fields=['event_type', '-created_at'], name='admin_panel_event_t_23a490_idx')],
            },
        ),
    ]
