# Generated by Django 5.2.14 on 2026-10-10 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_securityevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('method', models.CharField(default='GET', max_length=8)),
                ('status_code', models.PositiveSmallIntegerField(db_index=True, default=200)),
                ('response_ms', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('browser', models.CharField(blank=True, default='', max_length=60)),
                ('os', models.CharField(blank=True, default='', max_length=60)),
                ('device', models.CharField(blank=True, default='', max_length=30)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بازدید سایت',
                'verbose_name_plural': 'بازدیدهای سایت',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'status_code'], name='admin_panel_created_6b3985_idx'), models.Index(fields=['user', '-created_at'], name='admin_panel_user_id_59d1dd_idx')],
            },
        ),
    ]
