# Generated by Django 5.2.14 on 2026-05-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="allow_image_answer",
            field=models.BooleanField(default=False),
        ),
    ]
