# Generated by Django 5.2.14 on 2026-05-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_question_allow_image_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="matching_pairs",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("true_false", "صحیح/غلط"),
                    ("multiple_choice", "تستی"),
                    ("fill_blank", "جاخالی"),
                    ("short_answer", "پاسخ کوتاه"),
                    ("long_answer", "پاسخ بلند"),
                    ("image_answer", "پاسخ تصویری"),
                    ("matching", "وصل کردنی"),
                ],
                max_length=20,
            ),
        ),
    ]
