# Generated by Django 5.2.14 on 2026-05-24 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_question_matching_pairs_alter_question_question_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="allow_teacher_answer",
            field=models.BooleanField(
                default=True, verbose_name="معلم می\u200cتواند پاسخ تشریحی وارد کند"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="enable_anti_cheat",
            field=models.BooleanField(
                default=True, verbose_name="فعال کردن سیستم تشخیص تقلب"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="prevent_copy_paste",
            field=models.BooleanField(default=True, verbose_name="جلوگیری از کپی/پیست"),
        ),
        migrations.AddField(
            model_name="exam",
            name="prevent_tab_switch",
            field=models.BooleanField(default=True, verbose_name="جلوگیری از تغییر تب"),
        ),
        migrations.AddField(
            model_name="exam",
            name="show_answers_after_exam",
            field=models.BooleanField(
                default=False,
                verbose_name="نمایش پاسخ صحیح به دانش\u200cآموز بعد از اتمام",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="show_back_button",
            field=models.BooleanField(
                default=True, verbose_name="نمایش دکمه بازگشت به سوال قبلی"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="show_questions_mode",
            field=models.CharField(
                choices=[
                    ("all", "همه سوالات در یک صفحه"),
                    ("one_by_one", "هر سوال در یک صفحه"),
                ],
                default="one_by_one",
                max_length=20,
                verbose_name="نحوه نمایش سوالات",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="track_ip",
            field=models.BooleanField(default=True, verbose_name="ردیابی IP"),
        ),
        migrations.CreateModel(
            name="ExamSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="exams.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "exam")},
            },
        ),
        migrations.CreateModel(
            name="ExamLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=200)),
                ("page_url", models.CharField(blank=True, max_length=500)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="exams.examsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheatAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cheat_type",
                    models.CharField(
                        choices=[
                            ("tab_switch", "تغییر تب"),
                            ("copy_paste", "کپی/پیست"),
                            ("right_click", "کلیک راست"),
                            ("multiple_tabs", "باز کردن چند تب"),
                            ("different_ip", "آی\u200cپی متفاوت"),
                            ("inactivity", "عدم فعالیت طولانی"),
                            ("screenshot", "اسکرین\u200cشات"),
                            ("print_screen", "چاپ صفحه"),
                        ],
                        max_length=50,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cheats",
                        to="exams.examsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_text", models.TextField(blank=True, null=True)),
                (
                    "answer_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="teacher_answers/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_answers",
                        to="exams.question",
                    ),
                ),
            ],
        ),
    ]
