# Generated by Django 5.2.14 on 2026-05-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0004_exam_allow_teacher_answer_exam_enable_anti_cheat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="random_questions",
            field=models.BooleanField(default=False),
        ),
    ]
