# Generated by Django 5.2.14 on 2026-05-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_exam_random_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="timer_type",
            field=models.CharField(
                choices=[
                    ("floating", "تایم شناور (از لحظه شروع دانش\u200cآموز)"),
                    ("fixed", "تایم ثابت (همه تا زمان پایان مشخص)"),
                ],
                default="floating",
                max_length=20,
                verbose_name="نوع تایمر",
            ),
        ),
    ]
