# Generated by Django 5.2.14 on 2026-06-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_exam_timer_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="max_score",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
