# Generated by Django 5.2.14 on 2026-09-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_question_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='auto_graded',
            field=models.BooleanField(default=False, verbose_name='تصحیح خودکار'),
        ),
    ]
