# Generated by Django 5.2.14 on 2026-09-24 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_questionbank_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankfolder',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bankfolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='exams.bankfolder', verbose_name='پوشه والد'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'آسان'), ('medium', 'متوسط'), ('hard', 'دشوار')], default='medium', max_length=10, verbose_name='سطح دشواری'),
        ),
        migrations.AlterUniqueTogether(
            name='bankfolder',
            unique_together={('teacher', 'parent', 'name')},
        ),
    ]
