# Generated by Django 5.2.14 on 2026-09-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_bankfolder_parent_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='allow_image_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='matching_pairs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='options_type',
            field=models.CharField(choices=[('text', 'متن'), ('image', 'تصویر'), ('mixed', 'متن+تصویر')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question_type',
            field=models.CharField(choices=[('true_false', 'صحیح/غلط'), ('multiple_choice', 'تستی'), ('fill_blank', 'جاخالی'), ('short_answer', 'پاسخ کوتاه'), ('long_answer', 'پاسخ بلند'), ('image_answer', 'پاسخ تصویری'), ('matching', 'وصل کردنی')], max_length=20),
        ),
    ]
