# Generated by Django 5.2.14 on 2026-10-03 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('exams', '0013_bank_all_question_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 1), ('duration_minutes__lte', 600)), name='exam_duration_in_range'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='exam_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gte', 0), ('max_score__lte', 1000)), name='question_max_score_in_range'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 0)), name='question_order_non_negative'),
        ),
    ]
